"""empty message

Revision ID: b908053c2b34
Revises: 6922f5f0bee0
Create Date: 2026-04-16 20:12:28.446801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b908053c2b34'
down_revision = '6922f5f0bee0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.drop_constraint('answers_attempt_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'attempts', ['attempt_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('answers_attempt_id_fkey', 'attempts', ['attempt_id'], ['id'])

    # ### end Alembic commands ###
